// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eImovina.Api.Data;

#nullable disable

namespace eImovina.Api.Migrations
{
    [DbContext(typeof(eImovinaDbContext))]
    [Migration("20260816200950_AddAllNecessartModels")]
    partial class AddAllNecessartModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.AssignmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssignmentStatuses");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("InventoryNumber")
                        .IsUnique();

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.HasIndex("StatusId");

                    b.HasIndex("CategoryId", "StatusId", "CurrentLocationId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.EquipmentAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReturnedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EquipmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_EquipmentAssignments_OneActivePerEquipment")
                        .HasFilter("[StatusId] = 1");

                    b.HasIndex("ReturnedByUserId");

                    b.HasIndex("StatusId");

                    b.ToTable("EquipmentAssignments");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.EquipmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EquipmentCategories");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.EquipmentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCoverImage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("EquipmentId", "FileType");

                    b.ToTable("EquipmentFiles");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.EquipmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("StatusId");

                    b.ToTable("EquipmentRequests");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.EquipmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EquipmentStatuses");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RequestStatuses");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Inventories.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponsibleEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ResponsibleEmployeeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Inventories.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedInventoryNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoundLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDamaged")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsFound")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ExpectedLocationId");

                    b.HasIndex("FoundLocationId");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("InventoryId", "EquipmentId")
                        .IsUnique();

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Inventories.InventoryStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InventoryStatuses");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Locations.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Locations.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LocationTypes");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Users.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Users.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("eImovina.Shared.Models.WriteOffRequests.WriteOffRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DecisionByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DecisionByUserId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("StatusId");

                    b.ToTable("WriteOffRequests");
                });

            modelBuilder.Entity("eImovina.Shared.Models.WriteOffRequests.WriteOffRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WriteOffRequestStatuses");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.Equipment", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Equipments.EquipmentCategory", "Category")
                        .WithMany("Equipment")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Locations.Location", "CurrentLocation")
                        .WithMany("Equipment")
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Equipments.EquipmentStatus", "Status")
                        .WithMany("Equipment")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CurrentLocation");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.EquipmentAssignment", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Users.User", "AssignedByUser")
                        .WithMany("AssignmentsGiven")
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Users.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Equipments.Equipment", "Equipment")
                        .WithMany("Assignments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Users.User", "ReturnedByUser")
                        .WithMany("AssignmentsReturned")
                        .HasForeignKey("ReturnedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Shared.Models.Equipments.AssignmentStatus", "Status")
                        .WithMany("Assignments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Employee");

                    b.Navigation("Equipment");

                    b.Navigation("ReturnedByUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.EquipmentFile", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Equipments.Equipment", "Equipment")
                        .WithMany("Files")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Users.User", "UploadedByUser")
                        .WithMany("FilesUploaded")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.EquipmentRequest", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Equipments.EquipmentCategory", "Category")
                        .WithMany("EquipmentRequests")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Users.Employee", "Employee")
                        .WithMany("EquipmentRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Users.User", "ResolvedByUser")
                        .WithMany("EquipmentRequestsResolved")
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Shared.Models.Equipments.RequestStatus", "Status")
                        .WithMany("EquipmentRequests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Employee");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Inventories.Inventory", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Users.User", "ClosedByUser")
                        .WithMany("InventoriesClosed")
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Shared.Models.Users.User", "CreatedByUser")
                        .WithMany("InventoriesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Locations.Location", "Location")
                        .WithMany("Inventories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Users.Employee", "ResponsibleEmployee")
                        .WithMany("ResponsibleForInventories")
                        .HasForeignKey("ResponsibleEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Inventories.InventoryStatus", "Status")
                        .WithMany("Inventories")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClosedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Location");

                    b.Navigation("ResponsibleEmployee");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Inventories.InventoryItem", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Equipments.Equipment", "Equipment")
                        .WithMany("InventoryItems")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Locations.Location", "ExpectedLocation")
                        .WithMany()
                        .HasForeignKey("ExpectedLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Locations.Location", "FoundLocation")
                        .WithMany()
                        .HasForeignKey("FoundLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Shared.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Users.User", "ProcessedByUser")
                        .WithMany("InventoryItemsProcessed")
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipment");

                    b.Navigation("ExpectedLocation");

                    b.Navigation("FoundLocation");

                    b.Navigation("Inventory");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Locations.Location", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Locations.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Users.Employee", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Locations.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Users.User", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Users.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("eImovina.Shared.Models.Users.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Users.UserRole", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eImovina.Shared.Models.WriteOffRequests.WriteOffRequest", b =>
                {
                    b.HasOne("eImovina.Shared.Models.Users.User", "DecisionByUser")
                        .WithMany("WriteOffRequestsDecided")
                        .HasForeignKey("DecisionByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Shared.Models.Equipments.Equipment", "Equipment")
                        .WithMany("WriteOffRequests")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.Users.User", "RequestedByUser")
                        .WithMany("WriteOffRequestsSubmitted")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Shared.Models.WriteOffRequests.WriteOffRequestStatus", "Status")
                        .WithMany("WriteOffRequests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DecisionByUser");

                    b.Navigation("Equipment");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.AssignmentStatus", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.Equipment", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Files");

                    b.Navigation("InventoryItems");

                    b.Navigation("WriteOffRequests");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.EquipmentCategory", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("EquipmentRequests");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.EquipmentStatus", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Equipments.RequestStatus", b =>
                {
                    b.Navigation("EquipmentRequests");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Inventories.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Inventories.InventoryStatus", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Locations.Location", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Equipment");

                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Locations.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Users.Employee", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("EquipmentRequests");

                    b.Navigation("ResponsibleForInventories");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Users.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eImovina.Shared.Models.Users.User", b =>
                {
                    b.Navigation("AssignmentsGiven");

                    b.Navigation("AssignmentsReturned");

                    b.Navigation("EquipmentRequestsResolved");

                    b.Navigation("FilesUploaded");

                    b.Navigation("InventoriesClosed");

                    b.Navigation("InventoriesCreated");

                    b.Navigation("InventoryItemsProcessed");

                    b.Navigation("UserRoles");

                    b.Navigation("WriteOffRequestsDecided");

                    b.Navigation("WriteOffRequestsSubmitted");
                });

            modelBuilder.Entity("eImovina.Shared.Models.WriteOffRequests.WriteOffRequestStatus", b =>
                {
                    b.Navigation("WriteOffRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
